### ISSUE TITLE
`import_eks` plugin must be run twice to succeed

### ISSUE THREAD

**Issue by nathanweatherly** [stolostron/ocmplus.cm#51]
Every time I run the `import_eks` plugin, it fails the first time with the following error: 

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'managedcluster' referenced before assignment
failed: [localhost] (item=nweather-eks) => {"ansible_loop_var": "item", "changed": false, "item": "nweather-eks", "module_stderr": "Traceback (most recent call last):\n  File \"/Users/nweather/.ansible/tmp/ansible-tmp-1641924878.370075-66056-200587808912278/AnsiballZ_import_eks.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/Users/nweather/.ansible/tmp/ansible-tmp-1641924878.370075-66056-200587808912278/AnsiballZ_import_eks.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/nweather/.ansible/tmp/ansible-tmp-1641924878.370075-66056-200587808912278/AnsiballZ_import_eks.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.ocmplus.cm.plugins.modules.import_eks', init_globals=dict(_module_fqn='ansible_collections.ocmplus.cm.plugins.modules.import_eks', _modlib_path=modlib_path),\n  File \"/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/m4/_wdtp1ws6b7748zwg8nyvc1r0000gn/T/ansible_ocmplus.cm.import_eks_payload_3042gq4a/ansible_ocmplus.cm.import_eks_payload.zip/ansible_collections/ocmplus/cm/plugins/modules/import_eks.py\", line 332, in <module>\n  File \"/var/folders/m4/_wdtp1ws6b7748zwg8nyvc1r0000gn/T/ansible_ocmplus.cm.import_eks_payload_3042gq4a/ansible_ocmplus.cm.import_eks_payload.zip/ansible_collections/ocmplus/cm/plugins/modules/import_eks.py\", line 328, in main\n  File \"/var/folders/m4/_wdtp1ws6b7748zwg8nyvc1r0000gn/T/ansible_ocmplus.cm.import_eks_payload_3042gq4a/ansible_ocmplus.cm.import_eks_payload.zip/ansible_collections/ocmplus/cm/plugins/modules/import_eks.py\", line 255, in execute_module\n  File \"/var/folders/m4/_wdtp1ws6b7748zwg8nyvc1r0000gn/T/ansible_ocmplus.cm.import_eks_payload_3042gq4a/ansible_ocmplus.cm.import_eks_payload.zip/ansible_collections/ocmplus/cm/plugins/module_utils/import_utils.py\", line 117, in ensure_managedcluster\nUnboundLocalError: local variable 'managedcluster' referenced before assignment\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

The actual error to focus on is this: 

```
ocmplus/cm/plugins/module_utils/import_utils.py\", line 117, in ensure_managedcluster\nUnboundLocalError: local variable 'managedcluster' referenced before assignment
```

Running the plugin a second time succeeds. 

As @hanqiuzh pointed out, this seems like a timing bug we need to work out.

**Comment by TheRealHaoLiu** [comment]
@nathanweatherly can u run a sed to replace '\\n' with '\n' to make the log more readable

**Comment by TheRealHaoLiu** [comment]
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'managedcluster' referenced before assignment
failed: [localhost] (item=nweather-eks) => {"ansible_loop_var": "item", "changed": false, "item": "nweather-eks", "module_stderr": "Traceback (most recent call last):  File "/Users/nweather/.ansible/tmp/ansible-tmp-1641924878.370075-66056-200587808912278/AnsiballZ_import_eks.py", line 107, in <module>
    _ansiballz_main()
  File "/Users/nweather/.ansible/tmp/ansible-tmp-1641924878.370075-66056-200587808912278/AnsiballZ_import_eks.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/nweather/.ansible/tmp/ansible-tmp-1641924878.370075-66056-200587808912278/AnsiballZ_import_eks.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.ocmplus.cm.plugins.modules.import_eks', init_globals=dict(_module_fqn='ansible_collections.ocmplus.cm.plugins.modules.import_eks', _modlib_path=modlib_path),
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/folders/m4/_wdtp1ws6b7748zwg8nyvc1r0000gn/T/ansible_ocmplus.cm.import_eks_payload_3042gq4a/ansible_ocmplus.cm.import_eks_payload.zip/ansible_collections/ocmplus/cm/plugins/modules/import_eks.py", line 332, in <module>
  File "/var/folders/m4/_wdtp1ws6b7748zwg8nyvc1r0000gn/T/ansible_ocmplus.cm.import_eks_payload_3042gq4a/ansible_ocmplus.cm.import_eks_payload.zip/ansible_collections/ocmplus/cm/plugins/modules/import_eks.py", line 328, in main
  File "/var/folders/m4/_wdtp1ws6b7748zwg8nyvc1r0000gn/T/ansible_ocmplus.cm.import_eks_payload_3042gq4a/ansible_ocmplus.cm.import_eks_payload.zip/ansible_collections/ocmplus/cm/plugins/modules/import_eks.py", line 255, in execute_module
  File "/var/folders/m4/_wdtp1ws6b7748zwg8nyvc1r0000gn/T/ansible_ocmplus.cm.import_eks_payload_3042gq4a/ansible_ocmplus.cm.import_eks_payload.zip/ansible_collections/ocmplus/cm/plugins/module_utils/import_utils.py", line 117, in ensure_managedcluster
UnboundLocalError: local variable 'managedcluster' referenced before assignment
", "module_stdout": "", "msg": "MODULE FAILURE
See stdout/stderr for the exact error", "rc": 1}
```

**Comment by nathanweatherly** [comment]
I didn't realize how ugly it was 😂

**Comment by nathanweatherly** [comment]
Lower priority than high priority cluster proxy/productization work

**Comment by nathanweatherly** [comment]
Revalidate that this issue still exists. Tsu Phin might have fixed already.
